### PR TITLE
Add timestamps to post

### LINKED ISSUE #15: Add created_at timestamp

### PR DESCRIPTION
**Pull request by matDobek**
## Related Issue

Fix #15 
## Description

Added timestamp to tindex and post page.

Index:
image

Page:
image

### CODE REVIEW

**Comment by naliwajek** [comment]
:+1:

**Comment by matDobek** [comment]
one moreeee @dmp0x7c5 @siepet

**Comment by siepet** [comment]
Looks nice to me :) Go for it.

**Comment by matDobek** [comment]
\o/

**Comment by dmp0x7c5** [comment]
Just one word... Fantastic :)

**Pull request merged**
