### PR TITLE
Social media sharing

### LINKED ISSUE #13: Sharing post via social media
We could add sharing via:
- Twitter
- Facebook

Anything else?

### PR DESCRIPTION
**Pull request by matDobek**
## Related Issue

Fix #13 
## Description

How it looks:
image

### CODE REVIEW

**Comment by matDobek** [comment]
Could

**Comment by matDobek** [comment]
or even better: 
image

**Comment by siepet** [comment]
What if we kept twitter logo, with such caption: `if you enjoyed it, you can [twitter logo] it`?

**Comment by matDobek** [comment]
image

I like this one

**Comment by siepet** [comment]
Agree, let's stick with this one if nobody has any objections.

**Comment by naliwajek** [comment]
Why only Twitter? I don't have friends there :P 

Anyhow: :+1:

**Comment by matDobek** [comment]
I was struggling with adding custom facebook share button to our blog (tried generating link in iframe - but gihub pages does not allow CORS). As couldn't find another elegant way(their share button is obscure) to add facebook popup, just droppped the idea.

We can revisit this in future - I personally don't have a patience for this, right now.

Merging.

**Pull request merged**
